### ISSUE TITLE
WP Advanced Search Metabox 

### ISSUE THREAD

**Issue by mehmetsarr** [ivandoric/WordPress-Custom-Query#3]
Hello, how is metabox added in "WP Advanced Search"? There is no metabox example in the sample demo.

**Comment by ivandoric** [comment]
Did you watch all the videos in the series? Maybe this video can help: https://www.youtube.com/watch?v=v8IkotRDg4Q

If not maybe this can help: https://rudrastyh.com/wordpress/meta_query.html search for meta box on the page.

As far as I can remember you can query metaboxes same as you would query custom fields.

**Comment by mehmetsarr** [comment]
Thank you for your answer. I asked for this link. https://github.com/ivandoric/wp-advanced-search

**Comment by ivandoric** [comment]
Well this is something I forked a long time ago. You should ask the creator of the plugin: https://github.com/raideus/wp-advanced-search. This is the original repository.
